### ISSUE TITLE
Compile for Java 8+ support

### ISSUE THREAD

**Issue by steghio** [vspiliop/embedded-kafka-cluster#4]
Hello,

I tried using this dependency, but I get the following error:

```
cannot access io.github.vspiliop.testing.kafka.spring.context.EmbeddedKafkaCluster
  bad class file: maven\repo\io\github\vspiliop\testing\embedded-kafka-cluster\0.0.1\embedded-kafka-cluster-0.0.1.jar(io/github/vspiliop/testing/kafka/spring/context/EmbeddedKafkaCluster.class)
    class file has wrong version 54.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

I am running JDK 8, can you please check?

Thanks and cheers

**Comment by vspiliop** [comment]
Hello!

Looks like a Java version issue, as currently the build is using Java 10 as a source and target version for the maven-compiler-plugin (checkout the pom.xml). Can you try to use java 10 or 11?

Cheers

**Comment by steghio** [comment]
Hello,

yes it's definitely the Java version, that's my request to please compile it for Java 8+ so it's available from your repo directly.

If you are not using Java 10 specific features it would be great to have this for integration testing. I cannot unfortunately change my Java version for this project.

Thanks in advance

**Comment by vspiliop** [comment]
Hello!

Will do that but more likely beginning of August as I am on my wedding holidays :-)

Meanwhile one easy workaround would be to clone locally and change the compatibility version to 8 and deploy locally to your maven repo. I do not use java 10 features

**Comment by steghio** [comment]
Yes perfectly fine for me and thanks again. I will leave this issue open for tracking.

Enjoy your holidays and congratulations!

**Comment by steghio** [comment]
Hello,

hope your vacation was nice.

I opened PR to set target Java version to 8. Please try it out

Cheers

**Comment by vspiliop** [comment]
thanks! The PR is included in the 0.0.3 release.

**Comment by vspiliop** [comment]
If you have any comments on the library, how to be improved or even how you use it in your organisation I would be interested to know. In my previous project we were initially using the Confluent embedded Kafka for our integration tests. But as the microservices grew in numbers and complexity I created this lib to mainly overcome port conflicts when tests where ran in parallel on the same Jenkins slave, to be able to run even tests within the same microservice in parallel and also be able to easily configure 100% the same Kafka cluster as in prod.

**Comment by steghio** [comment]
Thanks, I mainly want to move away from Spring EmbeddedKafka since it requires too much mocking (eg Confluent Avro registry) to have a meaningful configuration for integration testing.

However, I first have to convince people here to pull the latest version in, currently we only have 0.0.1 available.

Thanks again and cheers
